name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/check@v3
      - uses: actions/setup-@v1
        with:
          ruby-version: ">=3.1.x"
      - name: Setup Rubocop
        run:
      - name: Rubocop Report
        run: rubocop --color
